"""empty message

Revision ID: 25d4825fa0aa
Revises: 063dff11e6a1
Create Date: 2019-02-15 14:41:43.969009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d4825fa0aa'
down_revision = '063dff11e6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flights_flight_destination_key', 'flights', type_='unique')
    op.drop_constraint('flights_flight_name_key', 'flights', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('flights_flight_name_key', 'flights', ['flight_name'])
    op.create_unique_constraint('flights_flight_destination_key', 'flights', ['flight_destination'])
    # ### end Alembic commands ###
