"""empty message

Revision ID: 858f5d2d5a6a
Revises: be72ecbeaf6d
Create Date: 2019-02-19 16:22:21.855761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858f5d2d5a6a'
down_revision = 'be72ecbeaf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport_photo', sa.String(length=180), nullable=True))
    op.add_column('users', sa.Column('role', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'passport_photo')
    # ### end Alembic commands ###
