"""empty message

Revision ID: be72ecbeaf6d
Revises: 25d4825fa0aa
Create Date: 2019-02-18 21:25:31.220977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be72ecbeaf6d'
down_revision = '25d4825fa0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_sent')
    # ### end Alembic commands ###
